tap "homebrew/bundle"

# Programming languages related
brew "lua"
brew "python"
brew "pyenv"
brew "go"
brew "rust"
# brew "android-studio"
# brew "kotlin"
# brew "scala"
# brew "sbt"
# brew "svn"

# AWS releated
brew "awscli"

brew "ripgrep"
brew "starship"
brew "autojump"
brew "asciinema"
brew "bash"
brew "bat"
brew "caddy"
brew "coreutils"
brew "checkbashisms"
brew "diff-so-fancy"
brew "eza"
brew "fd"
brew "fzf"
brew "fortune"
brew "git"
brew "git-extras"
brew "gnupg"
brew "graphviz"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "mqttui"
brew "nmap"
brew "dust"
brew "openssl"
brew "scmpuff"
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "websocat"
brew "volta"
brew "yarn"
brew "zsh-completions"

# Font
cask "font-jetbrains-mono-nerd-font"

# Applications
cask_args appdir: "/Applications"
cask "firefox"
cask "figma"
cask "google-chrome"
cask "gcloud-cli"
cask "google-japanese-ime"
cask "iina"
cask "notion"
cask "postman"
cask "raycast"
cask "slack"
cask "sf-symbols"
cask "tableplus"
cask "the-unarchiver"
cask "ghostty"
cask "visual-studio-code"
cask "inkscape"
cask "josm"
