#!/usr/bin/env bash

# Terminal
# ========
# ~/.osx — http://mths.be/osx

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# open "terminal/hanksudo.terminal"
# sleep 1
# defaults write com.apple.terminal 'Startup Window Settings' -string 'hanksudo'
# defaults write com.apple.terminal 'Default Window Settings' -string 'hanksudo'

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine snapshots
# hash tmutil &> /dev/null && sudo tmutil disablelocal

# Set auto-hide dock
defaults write com.apple.Dock autohide -int 1

# resort LaunchPad icon order
# defaults write com.apple.Dock ResetLaunchPad -bool true; killall Dock

# Customize Screen Shot save path
mkdir -p ~/Desktop/ScreenShots
defaults write com.apple.screencapture location ~/Desktop/ScreenShots

# Always keep windows
defaults write -g NSQuitAlwaysKeepsWindows -bool true

# Terminal - Focus Follow Mouse
defaults write com.apple.Terminal FocusFollowsMouse -string "NO"

# Show battery life percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Make bottom-right hotspot start screensaver
defaults write com.apple.dock wvous-br-corner -int 5 && \
defaults write com.apple.dock wvous-br-modifier -int 0

# Turn on dashboard-as-space
defaults write com.apple.dashboard enabled-state 2

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

############
# Keyboard #
############

# Enable character repeat on keydown
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2

# Set a shorter Delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Illuminate keyboard backlight in low light
defaults write com.apple.BezelServices kDim -bool true

# Dim off keyboard backlight after 5 seconds
defaults write com.apple.BezelServices kDimTime -int 5

#################
# Accessibility #
#################

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

##########
# Finder #
##########

# Finder: show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true
chflags nohidden ~/Library

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Don't default to saving documents to iCloud
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Set default Finder location to Downloads folder (~/Downloads)
defaults write com.apple.finder NewWindowTarget -string "PfLo" && \
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Downloads"

# Use current directory as default search scope in Finder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true && \
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true && \
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true && \
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show absolute path in finder's title bar.
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES

#########
# Xcode #
#########

# Xcode - show line number
defaults write com.apple.dt.Xcode DVTTextShowLineNumbers -bool true

killall SystemUIServer
