#!/usr/bin/env bash

# Terminal
# ========
# ~/.osx — http://mths.be/osx

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

open "terminal/hankwang.terminal"
sleep 1
defaults write com.apple.terminal 'Startup Window Settings' -string 'hankwang'
defaults write com.apple.terminal 'Default Window Settings' -string 'hankwang'

# Disable local Time Machine snapshots
sudo tmutil disablelocal

# Set auto-hide dock
defaults write com.apple.Dock autohide -int 1

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 0
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Set Screen shot save path
defaults write com.apple.screencapture location ~/Desktop/ScreenShots

# Always keep windows
defaults write -g NSQuitAlwaysKeepsWindows -bool true

# Terminal - Focus Follow Mouse
defaults write com.apple.Terminal FocusFollowsMouse -string YES

# Show battery life percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

#################
# Accessibility #
#################

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

##########
# Finder #
##########

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Don't generated DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

#########
# Xcode #
#########

# Xcode - show line number
defaults write com.apple.dt.Xcode DVTTextShowLineNumbers -bool true

killall SystemUIServer

