LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

# Homebrew API TOKEN
export HOMEBREW_GITHUB_API_TOKEN=

# auto completion for Python
export PYTHONSTARTUP=~/.pythonrc

# Android SDK home
export ANDROID_HOME=~/Library/Android/sdk

# Git global config
git config --global user.signingkey 8D82D8EE96EC0BCC
git config --global user.email 467745+hanksudo@users.noreply.github.com
git config --global user.name "Hank Wang"

alias t=gotitler
