LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

# Homebrew API TOKEN
export HOMEBREW_GITHUB_API_TOKEN=

# auto completion for Python
export PYTHONSTARTUP=~/.pythonrc

# Android SDK home
export ANDROID_HOME=~/Library/Android/sdk

# PostgreSQL bin
export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH

# Rust cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH

# Git global config
# git config --global user.signingkey XXXX
# git config --global user.email XXXX
# git config --global user.name "XXXX"

