# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="hanksudo"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(aws brew npm pip gem python sublime zsh-syntax-highlighting vagrant docker)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
export PATH=~/bin:$PATH:/usr/local/share/npm/bin:~/.rvm/bin

# Added Go paths
if type go > /dev/null; then
    export GOPATH=$HOME/goProjects
    export GOROOT=`go env GOROOT`
    export PATH=$PATH:$GOPATH/bin
fi

# zmv '(*).html $1.haml'
# http://zshwiki.org/home/builtin/functions/zmv
autoload -U zmv

# default editor
export EDITOR=vim

# npm speed up npm on node-gyp
export JOBS=max

#autojump - https://github.com/joelthelion/autojump
# A cd command that learns - easily navigate directories from the command line
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# extra functions
source ~/.functions

# extra profile
source ~/.profile

# show path
alias path='echo ${PATH}'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  alias ls="ls --color"
else # OS X `ls`
  if gls > /dev/null 2>&1; then
    alias ls='gls -F --color=always'
  else
    alias ls='ls -G'
  fi
fi

alias ll='ls -l'
alias la='ls -A'
alias lc='ls -CF'
alias lsd='ll | grep "^d"'  # List only directories
alias lsf='ll | grep "^-"'  # List only files
alias cp='cp -i'
alias mv='mv -i'

# Display a tree-like structural of any directory
alias tree="ls -R | grep ":" | sed -e 's/://' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

alias hosts='sudo $EDITOR /etc/hosts'
alias sshc='$EDITOR ~/.ssh/config'

# Empty the Trash on all mounted volumes and the main HDD
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

# gnu diff does not have DIFFOPTIONS like FreeBSD so:
alias diff='diff -u'

# `cat` with beautiful colors. requires Pygments installed.
alias c='pygmentize -O style=monokai -f console256 -g'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig | fgrep inet | fgrep netmask"
#alias ips="config | fgrep inet | fgrep netmask | awk '{print $2}'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# default 'Open With ...'
alias -s md=open
alias -s html=open

# shorten
alias v=vagrant
alias bb=buildbot

# alias clean_pyc="find . -name \*.pyc -delete"
alias grep="grep -i --color"

# Set Docker Env
$(boot2docker shellinit)

# Docker shortcuts
alias d="docker"
alias dcleanimages="docker images --no-trunc | grep '^<none>' | awk '{print $3}' | xargs docker rmi -f"
alias dcleancontainers="docker ps -a -q -f "status=exited*" | xargs docker rm"
alias dclean="dcleancontainers && dcleanimages"

fortune
