# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="hanksudo"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

DOCKER_VM='default'

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(aws brew nmap npm pip ruby gem rbenv python rust cargo zsh-syntax-highlighting docker docker-compose httpie jump zsh-autosuggestions kubectl)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.fastlane/bin:$PATH"

# Added Go paths
if type go > /dev/null; then
    export GOPATH=`go env GOPATH`  # default is $HOME/go
    export GOROOT=`go env GOROOT`
    export PATH=$PATH:$GOPATH/bin
fi

# Added Python@3 path
export PATH=/usr/local/opt/python@3/bin:$PATH

# zmv '(*).html $1.haml'
# http://zshwiki.org/home/builtin/functions/zmv
autoload -U zmv

# default editor
export EDITOR=vim

# npm speed up npm on node-gyp
export JOBS=max

#autojump - https://github.com/joelthelion/autojump
# A cd command that learns - easily navigate directories from the command line
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# extra functions, aliases
source ~/.functions
source ~/.aliases

# Magnificent app which corrects your previous console command.
# https://github.com/nvbn/thefuck
eval $(thefuck --alias)

# A command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# scmpuff
eval "$(scmpuff init -s)"

weather /東京\?0
weather /台北\?0

. ~/.zprofile

# rbenv
eval "$(rbenv init -)"
