# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="hanksudo"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

DOCKER_VM='default'

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(aws brew nmap npm pip gem python sublime zsh-syntax-highlighting vagrant docker docker-compose httpie jump zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH=~/bin:$PATH

# Added Go paths
if type go > /dev/null; then
    export GOPATH=`go env GOPATH`  # default is $HOME/go
    export GOROOT=`go env GOROOT`
    export PATH=$PATH:$GOPATH/bin
fi

# Added Python@2 path
export PATH=/usr/local/opt/python@2/bin:$PATH

# Use python 2 as default
alias python=python2
alias pip=pip2

# zmv '(*).html $1.haml'
# http://zshwiki.org/home/builtin/functions/zmv
autoload -U zmv

# default editor
export EDITOR=vim
alias e='${EDITOR}'

# npm speed up npm on node-gyp
export JOBS=max

#autojump - https://github.com/joelthelion/autojump
# A cd command that learns - easily navigate directories from the command line
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# extra functions
source ~/.functions

# extra profile
source ~/.profile

# show path
alias path='echo ${PATH}'

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias ll='ls -l'
alias la='ls -A'
alias lc='ls -CF'
alias lsd='ll | grep "^d"'  # List only directories
alias lsf='ll | grep "^-"'  # List only files
alias cp='cp -i'
alias mv='mv -i'

# Display a tree-like structural of any directory
alias tree="ls -R | grep ":" | sed -e 's/://' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

alias hosts='sudo $EDITOR /etc/hosts'
alias sshc='$EDITOR ~/.ssh/config'

# Empty the Trash on all mounted volumes and the main HDD
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

# gnu diff does not have DIFFOPTIONS like FreeBSD so:
alias diff='diff -u'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig | fgrep inet | fgrep netmask"
#alias ips="config | fgrep inet | fgrep netmask | awk '{print $2}'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# default 'Open With ...'
alias -s md=open
alias -s html=open
alias -s json=open
alias -s csv=open

# shorten
alias v=vagrant

# alias clean_pyc="find . -name \*.pyc -delete"
alias grep="grep -i --color"

# Magnificent app which corrects your previous console command.
# https://github.com/nvbn/thefuck
eval $(thefuck --alias)

# Docker shortcuts
alias d="docker"
alias dcleanimages="docker images | grep '<none>' | awk '{print $3}' | xargs docker rmi -f"
alias dcleancontainers="docker ps -a -q -f 'status=exited' | xargs docker rm"
alias dclean="dcleancontainers && dcleanimages"
alias dcleaner="docker run -v /var/run/docker.sock:/var/run/docker.sock:rw -v /var/lib/docker:/var/lib/docker:rw meltwater/docker-cleanup:latest"

# Jupyter shortcut notebook
alias nbx="jupyter nbconvert --execute --to notebook --inplace $1"

# purge all Python packages
alias pip-purge="pip uninstall -y -r <(pip freeze)"
alias pip3-purge="pip3 uninstall -y -r <(pip3 freeze)"

# A command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# scmpuff
eval "$(scmpuff init -s)"

weather /東京\?0
weather /台北\?0
